name: PR Build Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 11.0.24
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.24'
          distribution: 'temurin'

      # Step 3: Set up Maven
      - name: Set up Maven 3.9.9
        run: |
          curl -fsSL https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz | tar xz -C /tmp/
          sudo mv /tmp/apache-maven-3.9.9 /opt/maven
          sudo ln -sf /opt/maven/bin/mvn /usr/bin/mvn
          echo "Maven 3.9.9 installed"

      # Step 4: Verify Java and Maven Versions
      - name: Verify Java and Maven Versions
        run: |
          java -version
          mvn -version

      # Step 5: Cache Maven Dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 7: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Step 8: Add comments to PR
      - name: Comment on PR
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }} # Using the Personal Access Token
        if: ${{ always() }}
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token
          RESULT=$(cat result.txt)
          if [[ "$RESULT" == *"Tests failed!"* ]]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "PR Build Not Approved ❌: Test cases failed."
          elif [[ "$RESULT" == *"Build failed!"* ]]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "PR Build Not Approved ❌: Build failures."
          else
            gh pr comment ${{ github.event.pull_request.number }} --body "PR Build Approved! ✅"
          fi
