name: PR Build Check

on:
  pull_request:
    branches:
      - test-pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 4: Mock Build Success (disabled actual build step)
      - name: Mock Build Step
        id: mock_build
        run: |
          echo "Build successful!" > result.txt

      # Step 5: Add comments to PR using REST API
      - name: Comment on PR
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use the Classic PAT here
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          RESULT=$(cat result.txt)
          if [[ "$RESULT" == "Build failed!" ]]; then
            COMMENT_BODY="PR Build Not Approved ❌"
          else
            COMMENT_BODY="PR Build Approved! ✅"
          fi
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
